# Generated by Django 4.1.3 on 2023-02-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_registrationform_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='password',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
