# Generated by Django 4.1.3 on 2023-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_registrationform_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='status',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
